export interface PageInformation {
  url: string
  title: string
  hostname: string
  faviconUrl?: string
  collectedAt: string
}

export interface UserPreferences {
  theme: 'light' | 'dark' | 'system'
  showTechnicalDetails: boolean
}

export interface ExtensionError {
  code: string
  message: string
}

export type Result<T> = { success: true; data: T } | { success: false; error: ExtensionError }

export const ERROR_CODES = {
  ACTIVE_TAB_NOT_FOUND: 'ACTIVE_TAB_NOT_FOUND',
  UNSUPPORTED_URL: 'UNSUPPORTED_URL',
  BACKGROUND_UNAVAILABLE: 'BACKGROUND_UNAVAILABLE',
  CONTENT_SCRIPT_UNAVAILABLE: 'CONTENT_SCRIPT_UNAVAILABLE',
  MESSAGE_TIMEOUT: 'MESSAGE_TIMEOUT',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  DETECTION_TIMEOUT: 'DETECTION_TIMEOUT',
  CONTENT_SCRIPT_INJECTION_FAILED: 'CONTENT_SCRIPT_INJECTION_FAILED',
  PAGE_BRIDGE_FAILED: 'PAGE_BRIDGE_FAILED',
  INVALID_DETECTION_RESULT: 'INVALID_DETECTION_RESULT',
  UNSUPPORTED_DOCUMENT: 'UNSUPPORTED_DOCUMENT',
  SHOPIFY_DETECTION_FAILED: 'SHOPIFY_DETECTION_FAILED',
  SHOPIFY_NOT_CONFIRMED: 'SHOPIFY_NOT_CONFIRMED',
  CONTACT_SCAN_NOT_USER_INITIATED: 'CONTACT_SCAN_NOT_USER_INITIATED',
  TAB_URL_CHANGED: 'TAB_URL_CHANGED',
  CONTACT_SCAN_TIMEOUT: 'CONTACT_SCAN_TIMEOUT',
  CONTACT_PAGE_FETCH_FAILED: 'CONTACT_PAGE_FETCH_FAILED',
  INVALID_CONTACT_RESULT: 'INVALID_CONTACT_RESULT',
  CONTACT_SCAN_CANCELLED: 'CONTACT_SCAN_CANCELLED',
  CONTACT_SCAN_FAILED: 'CONTACT_SCAN_FAILED',
} as const

export type ErrorCode = keyof typeof ERROR_CODES
